/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Enables digital function */
#define IOCON_PIO_DIGITAL_EN 0x0100u
/*!
 * @brief Selects pin function 1 */
#define IOCON_PIO_FUNC1 0x01u
/*!
 * @brief Input function is not inverted */
#define IOCON_PIO_INV_DI 0x00u
/*!
 * @brief No addition pin function */
#define IOCON_PIO_MODE_INACT 0x00u
/*!
 * @brief Open drain is disabled */
#define IOCON_PIO_OPENDRAIN_DI 0x00u
/*!
 * @brief Standard mode, output slew rate control is enabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_7_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_0_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_10_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_10_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_1_FUNC_ALT5 0x05u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_26_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_27_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_27_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_2_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_5_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_5_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO1_7_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_8_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_8_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_9_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_9_MODE_PULL_UP 0x02u

/*! @name PIO0_29 (number 92), RX
  @{ */
#define BOARD_INITPINS_RX_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RX_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RX_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO0_30 (number 94), TX
  @{ */
#define BOARD_INITPINS_TX_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TX_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TX_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO0_26 (number 60), MOSI
  @{ */
#define BOARD_INITPINS_MOSI_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOSI_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOSI_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO1_1 (number 59), SSEL
  @{ */
#define BOARD_INITPINS_SSEL_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSEL_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSEL_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO1_2 (number 61), SCK
  @{ */
#define BOARD_INITPINS_SCK_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SCK_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SCK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO1_26 (number 68), LCD_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_DC_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_DC_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LCD_DC_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_DC_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_DC_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO1_27 (number 85), LCD_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_RST_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_RST_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LCD_RST_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_RST_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_RST_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO1_7 (number 9), TIMER
  @{ */
#define BOARD_INITPINS_TIMER_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TIMER_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TIMER_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_7 (number 6), AIN1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_AIN1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_AIN1_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_AIN1_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_AIN1_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_AIN1_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO1_0 (number 11), AIN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_AIN2_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_AIN2_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_AIN2_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_AIN2_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_AIN2_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO1_5 (number 31), ENCA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ENCA_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ENCA_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_ENCA_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ENCA_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ENCA_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO1_8 (number 24), ENCB
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ENCB_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ENCB_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_ENCB_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ENCB_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ENCB_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
